language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: kYfqNf3WZCzbZig/MIIBMNI0ZMF4sUUMNO9Vd0ewBEI2GBGi5colDED815qaAkJYsuBfEZpRUJERQ1JL5yKvnU45w7LzT9/ZzH0CGpRVK5d6nIwxsV0PMg+8W1noHGGyjB13CgJwXA38L5Yo9Oej6cVyW6Pd9vuWX6SRwz5kw8EqRFZo760WUvLmIW3CpkYcf1IfuK+Hf4svXf/TwKNlBUjH4MaMfhVJ1TH6tc7s2JevZqM69U9Xv0U/Hx32VIz4QpAi4RVdW5qtLO7vt1Iarfn+gXVQOAxrl8iF9WxPKCbma/FFwiOJIcJJs0YJqUPtWNkY04k427gOm6yTKEd9/fWEr3Z+VdBNY6/SuIJwHlr4QXQj4SvYmptkTgzX9au8hsKCJqW0dvRHnxD93/S2sSRnAI/D6pFvcSgfMUc84xamnAmoimIPEUdUqIEyO3/nke7WQTJxzoVx3PZXnFE476rZfLSdwJgOdJF/q7J1Qwoz35nt7VqrBYDP2CzwyuqcWGUMN8EHp4hIXEhDD/6vGTGjvElWHGRQS0PIJIDIGIdtSx4//BLrUDva8C1rpQuyQdS/jVrJKhrm6RW7WtD4twBgQ8kZaiDCE07I1l9LDm5S1vcpbRd2o1qMdb1Pf/40Vo7Bec+/UewbxoS6CVd5Bb4iKe9qZ2mLnUdoZjr4C+Q=
  skip_cleanup: true
  app:
    master: idividends-vault
  on:
    repo: sergiotorreslozano/idividends-vault
script: mvn test -B -Dspring.profiles.active=test
